version: '3'

services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production