version: '3'
services:
  server:
    build: ./Server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/app
    networks:
      - app-network

  client:
    build: ./Client
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network: